[project]

fullname = "Corpus der Entscheidungen des Bundesgerichtshofs"
shortname = "CE-BGH"
author = "Seán Fobbe"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"



[doi] # Digital Object Identifier

data.concept = "10.5281/zenodo.3942742" # do not change
data.version = "10.5281/zenodo.7699032" # checked

software.concept = "10.5281/zenodo.4705864" # do not change
software.version = "10.5281/zenodo.7699033" # checked

personendaten = "10.5281/zenodo.4568682"
aktenzeichen = "10.5281/zenodo.4569564"



[debug]

toggle = true   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"

pages = 50      # Die Anzahl der zufällig ausgewählten Seiten, die im Debugging-Modus berücksichtigt werden sollen (jede Seite enthält idR 30 Entscheidungen). Muss mindestens 10 betragen.

sample = 500   # Die Anzahl der zufällig ausgewählten Entscheidungen, die im Debugging-Modus berücksichtigt werden sollen

cleanrun = false # Löscht vor jedem Run alle gespeicherten Zwischen- und Endergebnisse (Hinweis: ist unabhängig von debug.toggle, aber idR für Debugging nützlich)


[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
number = 8   # Die Anzahl Rechenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


[parallel]

extractPDF = true
lingsummarize = true
citations = true
multihashes = true



[download]

timeout = 300			# Timeout für Downloads




[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] # Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report
