version: "3.7"

services:
  ce-bgh:
    container_name: ce-bgh
    image: ce-bgh:4.4.0
    tty: true
    volumes:
      - .:/ce-bgh
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin